services:

  backend:
    build:
      context: ./backend

    image: employee-backend:v4
    container_name: employee-backend

    restart: always

    environment:
      MYSQL_HOST: employee-management-db.cwfg442ye0ze.us-east-1.rds.amazonaws.com
      MYSQL_PORT: 3306
      MYSQL_DATABASE: employee_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Employee123

    ports:
      - "8000:8000"

    networks:
      - employee-network


  frontend:
    build:
      context: ./frontend

    image: employee-frontend:v1
    container_name: employee-frontend

    restart: always

    depends_on:
      - backend

    ports:
      - "3000:80"

    networks:
      - employee-network


networks:
  employee-network:
    driver: bridge
